#!/usr/bin/python

from argparse import ArgumentParser
from getoverhere.downloader import getDownloader



def main():
    parser = ArgumentParser()
    parser.add_argument('path',
                        help='Target path on disk.')
    parser.add_argument('deployments', nargs='*', help='Deployments.')
    parser.add_argument('-fi', '--full-install',
                        help='Overwrite all files.',
                        action='store_true')
    parser.add_argument('-sc', '--skip-confirm',
                        help='Skip confirmation for downloading files.',
                        action='store_true')
    parser.add_argument('-fu', '--force-update',
                        help='Force install if already up-to-date. '
                             'This should not be needed unless something went horribly wrong.',
                        action='store_true')
    parser.add_argument('-v', '--verbose',
                        help='Output all status messages.',
                        action='store_true')
    args = parser.parse_args()

    for deployment in args.deployments:
        downloader = getDownloader(deployment, args.path, args.full_install,
                                   args.skip_confirm, args.force_update,
                                   args.verbose)
        if downloader is None:
            print('[getoverhere] No downloader found for \'%s\'.' % deployment)
        else:
            downloader.download()



if __name__ == '__main__':
    main()
